# Generated by Django 5.0.7 on 2025-01-11 07:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0002_stockhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockhistory",
            name="change_date",
        ),
        migrations.AddField(
            model_name="stockhistory",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
