# Generated by Django 5.0.7 on 2025-01-11 07:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0003_remove_stockhistory_change_date_stockhistory_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockhistory",
            name="date",
        ),
        migrations.AddField(
            model_name="stockhistory",
            name="change_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
