# Generated by Django 5.0.7 on 2025-02-07 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0004_remove_stockhistory_date_stockhistory_change_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="category_item",
            new_name="category_name",
        ),
    ]
