# Generated by Django 5.0.7 on 2025-03-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("GarmentShopAPI", "0005_rename_category_item_item_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="gst",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="company",
            name="pan",
            field=models.CharField(max_length=10),
        ),
    ]
