# Generated by Django 5.0.7 on 2025-01-11 04:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("barcode", models.CharField(max_length=100)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "sub_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("size", models.CharField(blank=True, max_length=50, null=True)),
                ("item_name", models.CharField(max_length=255)),
                ("unit", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="ItemPreview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                ("unit", models.PositiveIntegerField()),
                ("unit_price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_item_price",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PreviewGrandTotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bill_number",
                    models.CharField(blank=True, max_length=10, unique=True),
                ),
                ("fullname", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("address", models.TextField()),
                ("tax_type", models.CharField(default="na", max_length=30)),
                ("tax", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "grand_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("payment_method1", models.CharField(default="cash", max_length=100)),
                ("payment_method2", models.CharField(default="upi", max_length=100)),
                ("narration", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "payment_method1_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "payment_method2_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("saletype", models.TextField(default="RetailSale", max_length=40)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="order_items", to="RetailSale.item"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_items",
                to="RetailSale.order",
            ),
        ),
    ]
