# Generated by Django 5.0.7 on 2025-01-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RetailSale", "0002_stockdeduction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="phone_number",
            field=models.CharField(max_length=10),
        ),
    ]
