# Generated by Django 5.0.7 on 2025-03-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("RetailSale", "0003_alter_order_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
