# Generated by Django 5.0.7 on 2025-02-19 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Garmentmodules", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="submodule",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="child_modules",
                to="Garmentmodules.submodule",
            ),
        ),
    ]
