# Generated by Django 5.0.7 on 2025-01-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Barcode", "0002_barcodegen_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="barcodegen",
            name="sub_category",
            field=models.CharField(blank=True, default="na", max_length=100, null=True),
        ),
    ]
