# Generated by Django 5.0.6 on 2025-03-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Barcode", "0003_alter_barcodegen_sub_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="BarcodeVerify",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=100)),
                ("category_name", models.CharField(max_length=100)),
                (
                    "sub_category",
                    models.CharField(
                        blank=True, default="na", max_length=100, null=True
                    ),
                ),
                ("item_size", models.CharField(max_length=10)),
                ("quantity", models.IntegerField(default=0)),
                ("date_verified", models.DateTimeField(auto_now_add=True)),
                ("barcodes", models.ManyToManyField(to="Barcode.barcodegen")),
            ],
        ),
    ]
