# Generated by Django 5.0.7 on 2025-03-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Purchasedetails", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseentry",
            name="discount_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
        migrations.AlterField(
            model_name="purchaseentry",
            name="gst_percentage",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=5, null=True
            ),
        ),
    ]
